services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: previewsegment-devtest
    user: "0:0"
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media:ro
    environment:
      - JELLYFIN_LOG_DIR=/config/log
    restart: "no"
